_BASE_: "../base_dh_COCO.yaml"
MODEL:
  WEIGHTS: "./results/COCO/dh/dh_r50_fpn_COCO/model_final.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
OUTPUT_DIR: "./results/COCO/dh/dh_r50_fpn_COCO/"