MODEL:
  META_ARCHITECTURE: "ATSS"
  WEIGHTS: "./pretrained/dyhead_swint_atss_fpn_2x_ms.pth"
  PIXEL_MEAN: [123.675, 116.28, 103.53]
  PIXEL_STD: [58.395, 57.12, 57.375]
  BACKBONE:
    NAME: "build_retinanet_swint_fpn_dyhead_backbone"
  SWINT:
    OUT_FEATURES: ["stage3", "stage4", "stage5"]
  FPN:
    IN_FEATURES: ["stage3", "stage4", "stage5"]
  DYHEAD:
    NUM_CONVS: 6
    CHANNELS: 256
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x*2,] for x in [32, 64, 128, 256, 512 ]]"]
    ASPECT_RATIOS: [1.0,]
    OFFSET: 0.5
  ATSS:
    NUM_CONVS: 0
DATASETS:
  TRAIN: ("visual_genome_train",)
  TEST: ("visual_genome_val",)
DATALOADER:
  NUM_WORKERS: 32
SOLVER:
  IMS_PER_BATCH: 40
  BASE_LR: 0.0001
  WEIGHT_DECAY: 0.05
  WEIGHT_DECAY_BIAS: 0.05
  STEPS: (60000, 80000)
  MAX_ITER: 240000
  OPTIMIZER: "ADAMW"
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
EVALUATOR_TYPE: 'default'
SEED: 2022
VERSION: 2
