_BASE_: "../base_dh_VG_concepts.yaml"
MODEL:
  WEIGHTS: "./results/VG/dh/dh_r50_fpn_VG_concepts_cat/model_final.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  ACTIVATE_CONCEPT_GENERATOR: FALSE
DATASETS:
  TRAIN: ("visual_genome_train",)
  TEST: ("visual_genome_val",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/VG/dh/dh_r50_fpn_VG_concepts_cat/"