_BASE_: "../base_frcnn_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/frcnn/frcnn_r50_fpn_COCO_concepts_cat_depth1/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: FALSE
  APPLY_CONDITION_FROM_FILE: FALSE
  APPLY_FILTER: FALSE
  DEPTH: "1"
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
  # TEST: ("coco_2017_val_subset",)
  # TEST: ("coco_2017_val_powerset",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_r50_fpn_COCO_concepts_cat_depth1/"