_BASE_: "../base_retinanet_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/retinanet/retinanet_r101_fpn_COCO_concepts_cat/model_final.pth"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: FALSE
  APPLY_CONDITION_FROM_FILE: FALSE
  ACTIVATE_CONCEPT_GENERATOR: FALSE
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/COCO/retinanet/retinanet_r101_fpn_COCO_concepts_cat/"
