_BASE_: "../base_retinanet_VG.yaml"
MODEL:
  META_ARCHITECTURE: "drigoniRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
OUTPUT_DIR: "./results/OID/retinanet/retinanet_drigoni_r50_fpn_VG/"