_BASE_: "../base_dh_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "./results/COCO/dh/dh_r101_fpn_COCO_concepts_cat/model_final.pth"
  BACKBONE:
    NAME: "build_resnet_fpn_dyhead_backbone"
  RESNETS:
    DEPTH: 101
    OUT_FEATURES: ["res3", "res4", "res5"]
  ATSS:
    NUM_CONVS: 2
CONCEPT:
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  APPLY_FILTER: FALSE
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
DEEPSETS:
  EMB: "random"
OUTPUT_DIR: "./results/COCO/dh/dh_r101_fpn_COCO_concepts_cat/"