MODEL:
  META_ARCHITECTURE: "ConceptRetinaNet"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  BACKBONE:
    NAME: "build_retinanet_resnet_fpn_backbone"
  RESNETS:
    DEPTH: 50
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  ANCHOR_GENERATOR:
    SIZES: !!python/object/apply:eval ["[[x, x * 2**(1.0/3), x * 2**(2.0/3) ] for x in [32, 64, 128, 256, 512 ]]"]
  RETINANET:
    IOU_THRESHOLDS: [0.4, 0.5]
    IOU_LABELS: [0, -1, 1]
    SMOOTH_L1_LOSS_BETA: 0.0
  ROI_HEADS:
    NAME: "StandardROIHeads"
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 2
    POOLER_RESOLUTION: 7
  ROI_MASK_HEAD:
    NAME: "MaskRCNNConvUpsampleHead"
    NUM_CONV: 4
    POOLER_RESOLUTION: 14
DATASETS:
  TRAIN: ("coco_2017_tuning_train",)
  TEST: ("coco_2017_tuning_val",)
DATALOADER:
  NUM_WORKERS: 32
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.01
  STEPS: (60000, 80000)
  MAX_ITER: 90000
  WEIGHT_DECAY: 0.0001
  WEIGHT_DECAY_BIAS: 0.0001
CONCEPT:
  FILE: './concept/coco_to_synset.json'
  CONCEPT_FUSION: "cat" # ["cat", "mul", "add", "zeros"]
  APPLY_CONDITION: TRUE
  APPLY_CONDITION_FROM_FILE: FALSE
  EXTERNAL_CONCEPTS_FOLDER: './datasets/ewiser_concepts_COCO_valid/'
  APPLY_FILTER: TRUE
  DEPTH: 2
  UNIQUE: TRUE
DEEPSETS:
  EMB: 'wordnet'   # 'random' # 'wordnet'
  EMB_DIM: 150
  FREEZE: FALSE
  MLP1_LAYERS: [150, 256]
  MLP1_OUTPUT_DIM: 256 
  MLP2_LAYERS: [256, 256]
  OUTPUT_DIM: 256
  AGGREGATE: 'sum'
EVALUATOR_TYPE: 'default'
VERSION: 2
SEED: 2022