_BASE_: "base_frcnn_COCO_concepts.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-101.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 101
CONCEPT:
  CONCEPT_FUSION: "zeros" # ["cat", "mul", "add", "zeros"]
OUTPUT_DIR: "./results/COCO/frcnn/frcnn_r101_fpn_COCO_concepts_zeros/"